# Basic config
baseURL = "https://govindmenon69.github.io/OrangeMC-DOCS-SRC/"
theme = "hugo-bearcub"
copyright = "Orange Labs (CC BY 4.0)"
defaultContentLanguage = "en"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Setup syntax highlighting without inline styles. For more information about
# why you'd want to avoid inline styles, see
# https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#unsafe_inline_styles
[markup]
  [markup.highlight]
    lineNos = true
    lineNumbersInTable = false
    # This allows Bear Cub to use a variation of Dracula that is more accessible
    # to people with poor eyesight. For more information about color contrast
    # and accessibility, see https://web.dev/color-and-contrast-accessibility/
    noClasses = false

# Multilingual mode config. More for information about how to setup translation,
# see https://gohugo.io/content-management/multilingual/
[languages]
  [languages.en]
    title = "OrangeMC Guide"
    languageName = "en-US ğŸ‡ºğŸ‡¸"
    LanguageCode = "en-US"
    contentDir = "content"  
    [languages.en.params]
      madeWith = "Wow you finished reading? ğ—¥ğ—˜ğ—”ğ—— ğ—œğ—§ ğ—”ğ—šğ—”ğ—œğ—¡"
       
[params]
  # The description of your website
  description = "This is just a how to guide on how to get on OrangeMC dont worry about it lol :p "

  # The path to your favicon
  favicon = "images/favicon.png"


  images = ["images/share.webp"]


  title = "OrangeMC Docs"

  dateFormat = "2006-01-02"


  hideUntranslated = false

  themeStyle = "original"

  generateSocialCard = true

